### ISSUE TITLE
Add schema by march 17th

### ISSUE THREAD

**Issue by vinnyoodles** [QSport/QSport#3]
1. Finalize your app scope. Separate your features into required and optionals. Make sure you can answer the questions in the "Considerations" section below. Update your README with any changes you've made to the user stories.
2. Set up the server.
3. Define the tables and columns you'll need and add these to your project README.

**Comment by vinnyoodles** [comment]
f2c22c6372ae49cb13fa74d3de6e1e140a3fbde6 /cc @codepathreview

**Comment by vinnyoodles** [comment]
We will be using our own server and MongoDB for our data.

**Comment by anidev** [comment]
We're using mongo?

**Comment by vinnyoodles** [comment]
@anidev I thought so, or did you guys decide on using postgres?

**Comment by hatu87** [comment]
:+1: Nice work on getting the data schema defined! Next week we jump into the first implementation sprint. You'll have 3 sprints (one week each) to complete all the required stories for your app and 2 sprints (one week each) to work on optionals and add polish. Let us know if we can help in any way!

Besides, there a few things you must consider:
 - Sport types: it's better if you store a sport types table and link session table to it instead of storing sport types
 - Location: you must store location in latitude and longitude so that user can mark sessions in map and allow user to find nearby sessions.
 - Message: message table must have message content, message's sender.

**Comment by vinnyoodles** [comment]
Thanks @hatu87
